FROM python:3.8-buster AS compile-image

ADD requirements.txt .

RUN apt-get update && apt-get upgrade -y && \
    apt-get install python3-pip -y && \
    python3 -m pip install --user --no-cache-dir git+https://github.com/JaewonAC/sony_camera_api.git && \
    pip3 install --user --no-cache-dir -r requirements.txt && \
    python3 -m pip install --user --force-reinstall --no-cache-dir adafruit-blinka

FROM python:3.8-alpine AS build-image

COPY --from=compile-image /root/.local /root/.local
ENV PATH=/root/.local/bin:$PATH
RUN mkdir /fixins
WORKDIR /fixins